Repository Wake-up-together-TogetUp/togetup-server, pull requests merged in 2023-05, with the labels that each got.

#9 Feature : update Alarm & ect
  build.gradle
  src/main/java/com/wakeUpTogetUp/togetUp/alarms/AlarmController.java
  src/main/java/com/wakeUpTogetUp/togetUp/alarms/AlarmDao.java
  src/main/java/com/wakeUpTogetUp/togetUp/alarms/AlarmProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/alarms/AlarmRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/alarms/AlarmService.java
  src/main/java/com/wakeUpTogetUp/togetUp/alarms/dto/request/AlarmReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/alarms/dto/response/AlarmRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/alarms/dto/response/AlarmsRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/alarms/model/Alarm.java
  src/main/java/com/wakeUpTogetUp/togetUp/alarms/model/PostAlarmReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/ResponseStatus.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/dto/BaseResponse.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/exception/BaseException.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/exception/GlobalExceptionHandler.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/interfaces/CustomRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/files/FileController.java
  src/main/java/com/wakeUpTogetUp/togetUp/mappingAlarmRoutine/model/MappingAlarmRoutineRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/missions/MissionDao.java
  src/main/java/com/wakeUpTogetUp/togetUp/missions/MissionRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/routines/RoutineController.java
  src/main/java/com/wakeUpTogetUp/togetUp/routines/RoutineDao.java
  src/main/java/com/wakeUpTogetUp/togetUp/routines/RoutineProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/routines/RoutineRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/routines/RoutineService.java
  src/main/java/com/wakeUpTogetUp/togetUp/routines/dto/request/RoutineReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/routines/dto/response/RoutineRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/routines/model/PostRoutineReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/routines/model/Routine.java
  src/main/java/com/wakeUpTogetUp/togetUp/users/UserController.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mappers/AlarmMapper.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mappers/RoutineMapper.java
Labels: enhancement, refactor, chore

#10 Feature : alarm
  src/main/java/com/wakeUpTogetUp/togetUp/alarms/AlarmController.java
  src/main/java/com/wakeUpTogetUp/togetUp/alarms/AlarmProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/alarms/AlarmRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/alarms/AlarmService.java
  src/main/java/com/wakeUpTogetUp/togetUp/alarms/dto/request/AlarmReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/alarms/model/Alarm.java
  src/main/java/com/wakeUpTogetUp/togetUp/routines/RoutineController.java
  src/main/java/com/wakeUpTogetUp/togetUp/routines/RoutineProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/routines/RoutineRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/routines/RoutineService.java
  src/main/java/com/wakeUpTogetUp/togetUp/routines/dto/request/RoutineReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/routines/model/Routine.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mappers/RoutineMapper.java
Labels: enhancement

#11 Feature/group
  src/main/java/com/wakeUpTogetUp/togetUp/common/ResponseStatus.java
  src/main/java/com/wakeUpTogetUp/togetUp/group/GroupController.java
  src/main/java/com/wakeUpTogetUp/togetUp/group/GroupRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/group/GroupService.java
  src/main/java/com/wakeUpTogetUp/togetUp/group/dto/request/GroupReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/group/dto/response/GroupRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/group/model/Group.java
  src/main/java/com/wakeUpTogetUp/togetUp/mappingGroupMission/model/MappingGroupMission.java
  src/main/java/com/wakeUpTogetUp/togetUp/mappingGroupUser/GroupUserDto.java
  src/main/java/com/wakeUpTogetUp/togetUp/mappingGroupUser/MappingGroupUserController.java
  src/main/java/com/wakeUpTogetUp/togetUp/mappingGroupUser/MappingGroupUserRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/mappingGroupUser/MappingGroupUserService.java
  src/main/java/com/wakeUpTogetUp/togetUp/mappingGroupUser/dto/request/MappingGroupUserReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/mappingGroupUser/dto/response/MappingGroupUserRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/mappingGroupUser/model/MappingGroupUser.java
  src/main/java/com/wakeUpTogetUp/togetUp/missions/model/Mission.java
  src/main/java/com/wakeUpTogetUp/togetUp/users/model/User.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mappers/GroupMapper.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mappers/MappingGroupUserMapper.java
Labels: enhancement

#12 feat,refactor : jwt 토큰 userId로 만들기
  src/main/java/com/wakeUpTogetUp/togetUp/common/ResponseStatus.java
  src/main/java/com/wakeUpTogetUp/togetUp/login/oauth/entity/ProviderType.java
  src/main/java/com/wakeUpTogetUp/togetUp/login/oauth/entity/RoleType.java
  src/main/java/com/wakeUpTogetUp/togetUp/login/oauth/info/OAuth2UserInfo.java
  src/main/java/com/wakeUpTogetUp/togetUp/login/oauth/info/OAuth2UserInfoFactory.java
  src/main/java/com/wakeUpTogetUp/togetUp/login/oauth/info/impl/GoogleOAuth2UserInfo.java
  src/main/java/com/wakeUpTogetUp/togetUp/users/UserController.java
  src/main/java/com/wakeUpTogetUp/togetUp/users/UserDao.java
  src/main/java/com/wakeUpTogetUp/togetUp/users/UserRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/users/UserService.java
  src/main/java/com/wakeUpTogetUp/togetUp/users/dto/request/UserReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/users/dto/response/UserRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/users/model/GetUserRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/users/oauth/OAuthService.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/JwtService.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mappers/UserMapper.java
Labels: enhancement, refactor

#15 Feature/user
  src/main/java/com/wakeUpTogetUp/togetUp/users/UserController.java
  src/main/java/com/wakeUpTogetUp/togetUp/users/UserService.java
  src/main/java/com/wakeUpTogetUp/togetUp/users/dto/request/SocialLoginReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/users/dto/response/UserTokenRes.java
Labels: enhancement
