Repository Wake-up-together-TogetUp/togetup-server, pull requests merged in 2023-09, with the labels that each got.

#35 #23 [FEAT] naver object detection api 적용
  .gitignore
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/Letterbox.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/ObjectDetectionModel.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/objectDetection/NaverObjectDetectionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/objectDetection/ObjectDetectionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/objectDetection/dto/response/ObjectDetectionRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/dto/response/NotificationRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/model/UserAvatar.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/model/UserAvatarPurchaseLog.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/Status.java
  src/main/java/com/wakeUpTogetUp/togetUp/config/ODConfig.java
  src/main/java/com/wakeUpTogetUp/togetUp/exception/GlobalExceptionHandler.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/ImageCompressor.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/EntityDtoMapper.java
  src/main/resources/banner-local.txt
Labels: FEATURE

#47 #46 [FIX] alarm API 수정
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/request/PatchAlarmReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/config/OpenApiConfig.java
Labels: FIX

#50 #40 #49 [FEATURE, DOCS] Feature/group : room api , room,user swagger 설명 추가
  .gitignore
  build.gradle
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/model/Alarm.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/auth/AuthController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/auth/dto/request/SocialLoginReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionLogRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/model/Mission.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/model/MissionLog.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/entity/Notification.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomUserRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/UserCompleteType.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/request/RoomReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/request/RoomUserLogMissionReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomUserMissionLogRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/model/RoomUser.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/model/User.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/Constant.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/Status.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/TimeFormatter.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/TimestampFormatter.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/EntityDtoMapper.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/GroupMapper.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/UserMapper.java
  src/main/resources/migration/mock.sql
  src/main/resources/migration/togetup-erd.sql
Labels: DOCS, FEATURE
