Repository Wake-up-together-TogetUp/togetup-server, pull requests merged in 2023-08, with the labels that each got.

#22 chore : 안쓰는 폴더 삭제, db 꼬이는 것 수정
  logs/app.2023-06-13.0.gz
  logs/app.2023-06-17.0.gz
  logs/app.log
  logs/error.log
  src/main/java/com/wakeUpTogetUp/togetUp/alarm/AlarmProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/alarm/AlarmService.java
  src/main/java/com/wakeUpTogetUp/togetUp/alarm/dto/request/PatchAlarmReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/alarm/dto/request/PostAlarmReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/alarm/dto/response/AlarmRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/alarm/model/Alarm.java
  src/main/java/com/wakeUpTogetUp/togetUp/avatar/model/Avatar.java
  src/main/java/com/wakeUpTogetUp/togetUp/chat/ChatController.java
  src/main/java/com/wakeUpTogetUp/togetUp/chat/ChatRoomController.java
  src/main/java/com/wakeUpTogetUp/togetUp/chat/ChatRoomRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/chat/ChatRoomRepository2.java
  src/main/java/com/wakeUpTogetUp/togetUp/chat/ChatService.java
  src/main/java/com/wakeUpTogetUp/togetUp/chat/IndexController.java
  src/main/java/com/wakeUpTogetUp/togetUp/chat/JwtTokenProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/chat/dto/request/PostChatRoomReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/chat/dto/response/ChatRoomRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/chat/model/ChatMessage.java
  src/main/java/com/wakeUpTogetUp/togetUp/chat/model/ChatRoom.java
  src/main/java/com/wakeUpTogetUp/togetUp/chat/model/LoginInfo.java
  src/main/java/com/wakeUpTogetUp/togetUp/chat/pubsub/RedisSubscriber.java
  src/main/java/com/wakeUpTogetUp/togetUp/config/EmbeddedRedisConfig.java
  src/main/java/com/wakeUpTogetUp/togetUp/config/RedisConfig.java
  src/main/java/com/wakeUpTogetUp/togetUp/config/WebSockConfig.java
  src/main/java/com/wakeUpTogetUp/togetUp/config/interceptor/StompHandler.java
  src/main/java/com/wakeUpTogetUp/togetUp/fcmNotification/entity/PushLog.java
  src/main/java/com/wakeUpTogetUp/togetUp/group/GroupService.java
  src/main/java/com/wakeUpTogetUp/togetUp/group/dto/request/GroupReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/group/model/Group.java
  src/main/java/com/wakeUpTogetUp/togetUp/mappingGroupUser/model/MappingGroupUser.java
  src/main/java/com/wakeUpTogetUp/togetUp/mission/model/Mission.java
  src/main/java/com/wakeUpTogetUp/togetUp/mission/model/MissionCompleteLog.java
  src/main/java/com/wakeUpTogetUp/togetUp/routine/RoutineController.java
  src/main/java/com/wakeUpTogetUp/togetUp/routine/RoutineProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/routine/RoutineRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/routine/RoutineService.java
  src/main/java/com/wakeUpTogetUp/togetUp/routine/dto/request/PostRoutineReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/routine/dto/response/RoutineRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/routine/model/Routine.java
  src/main/java/com/wakeUpTogetUp/togetUp/users/UserController.java
  src/main/java/com/wakeUpTogetUp/togetUp/users/model/User.java
  src/main/java/com/wakeUpTogetUp/togetUp/users/oauth/GetSocialOAuthRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/users/oauth/GoogleOAuthToken.java
  src/main/java/com/wakeUpTogetUp/togetUp/users/oauth/GoogleOauth.java
  src/main/java/com/wakeUpTogetUp/togetUp/users/oauth/GoogleUser.java
  src/main/java/com/wakeUpTogetUp/togetUp/users/oauth/OAuthService.java
  src/main/java/com/wakeUpTogetUp/togetUp/users/oauth/SocialOauth.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/EntityDtoMapper.java
  src/main/resources/application.yml
Labels: chore

#29 #23 [REFACTOR] 알람, 미션 API 수정 및 Swagger 어노테이션 추가
  .gitignore
  build.gradle
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/request/DeleteAlarmReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/request/PatchAlarmReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/request/PostAlarmReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/response/GetAlarmRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/model/Alarm.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/auth/AuthUserResolver.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/auth/service/AuthService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/fcmNotification/NotificationController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/file/FileController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/file/FileService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/dto/request/PostMissionLogReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/dto/response/GetMissionRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/dto/response/MissionLogRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/dto/BaseResponse.java
  src/main/java/com/wakeUpTogetUp/togetUp/config/OpenApiConfig.java
  src/main/java/com/wakeUpTogetUp/togetUp/config/WebConfig.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/JwtService.java
  src/main/resources/application.yml
  src/main/resources/migration/togetup-erd.sql
  src/main/resources/static/docs/index.html
Labels: REFACTOR

#33 #23 [CHORE] 리뷰 반영 및 기타 수정사항
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/ObjectDetectionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/Letterbox.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/ODResult.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/ObjectDetectionModel.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/FcmService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/PushLogService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/dto/request/PushNotificationReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/dto/response/NotificationRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/dto/response/PushNotificationRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/entity/Notification.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserService.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/Status.java
  src/main/java/com/wakeUpTogetUp/togetUp/config/OpenApiConfig.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/EntityDtoMapper.java
  src/main/resources/migration/togetup-erd.sql
Labels: CHORE
