Repository Wake-up-together-TogetUp/togetup-server, pull requests merged in 2023-11, with the labels that each got.

#70 [ENV] DB schema 수정사항 기록 모음 패키지 updates 추가
  src/main/resources/migration/data.sql
  src/main/resources/migration/mock.sql
  src/main/resources/migration/updates/20231014[avatar alarm user].sql
  src/main/resources/migration/updates/20231021[avatar userAvatar userAvatarPurchaseLog].sql
Labels: ENV

#79 [FEAT] Home - 알람 타임라인 api 구현
  .gitignore
  build.gradle
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/request/PostAlarmReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/response/AlarmSimpleRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/response/AlarmTimeLineRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/response/GetAlarmRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/model/Alarm.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/home/HomeController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomDetailRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomInfoRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/Status.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/dto/BaseResponse.java
  src/main/java/com/wakeUpTogetUp/togetUp/exception/GlobalExceptionHandler.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/EntityDtoMapper.java
Labels: FEATURE

#81 [FEAT] 미션 판독 API 결과를 임시로 변경
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionController.java
Labels: FEATURE

#82 Feature/mission api migration
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/model/Emotion.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/model/MissionObject.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/AzureAiService.java
  src/main/resources/migration/data.sql
Labels: REFACTOR, FEATURE

#83 [FEAT] 미션 API 마이그레이션
  .gitignore
  build.gradle
  src/main/java/com/wakeUpTogetUp/togetUp/TogetUpApplication.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/auth/service/AppleLoginServiceImpl.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/file/FileService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/model/Emotion.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/model/MissionObject.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/AzureAiService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/GoogleVisionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/MissionImageService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/NaverAiService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/dto/response/FaceRecognitionRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/dto/response/ObjectDetectionRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/Status.java
  src/main/java/com/wakeUpTogetUp/togetUp/config/FirebaseConfig.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/ImageProcessing/ImageProcessor.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/ImageProcessing/vo/ImageDrawResult.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/ImageProcessing/vo/ImageProcessResult.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/ImageProcessing/vo/ImageProcessedResult.java
  src/main/resources/migration/data.sql
Labels: FEATURE

#84 #76 [FEAT] fcm push 구현, 미션 성공시 fcm push 전송
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/DataKeyType.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/DataValueType.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/FcmService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/PushLogService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/dto/request/BroadCastNotificationReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/dto/request/PushNotificationReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/dto/response/NotificationRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/dto/response/PushNotificationRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/vo/NotificationSendVo.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/vo/RoomMissionLogNotificationVo.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/model/Room.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/fcmToken/FcmToken.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/fcmToken/FcmTokenRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/EntityDtoMapper.java
  src/main/resources/migration/updates/20231102[room].sql
  src/main/resources/migration/updates/20231127[fcm_token].sql
Labels: FEATURE

#85 [FEAT] 로그인 응답에 유저 스탯, 아바타 정보 추가
  src/main/java/com/wakeUpTogetUp/togetUp/api/auth/dto/response/LoginRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/auth/service/AuthService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/dto/response/MissionLogCreateRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserAvatarService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/model/User.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/vo/UserStat.java
Labels: REFACTOR, FEATURE

#87 [FIX] 홈 - 알람 타임라인 API 응답 형식 수정
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/response/AlarmSimpleRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/response/AlarmTimeLineRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/model/Alarm.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/model/AlarmType.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserAvatarService.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/DateTimeProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/EntityDtoMapper.java
Labels: FIX
