Repository Wake-up-together-TogetUp/togetup-server, pull requests merged in 2023-10, with the labels that each got.

#53 [FEAT, FIX] 이미지 처리 메소드 추가 및 속도 개선
  build.gradle
  src/main/java/com/wakeUpTogetUp/togetUp/api/file/FileService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/objectDetection/NaverAiService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/NaverAiService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/ObjectDetectionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/dto/response/FaceRecognitionRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/dto/response/ObjectDetectionRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/ImageCompressor.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/ImageProcessing/ImageProcessor.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/ImageProcessing/vo/ImageDrawResult.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/ImageProcessing/vo/ImageProcessedResult.java
Labels: FEATURE, FIX

#59 #56 [CHORE,FEAT] Feature/edit group 방 디테일 api 수정, 방 참가 api 개발
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomDetailRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/model/RoomUser.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/TimeFormatter.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/EntityDtoMapper.java
  src/main/resources/static/docs/index.html
Labels: CHORE, FEATURE

#68 #55 [FEAT, FIX] 아바타 관련 API
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/request/PostAlarmReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/model/Alarm.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/auth/service/AuthService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/AvatarTheme.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/model/Avatar.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/vo/UserAvatarData.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mappingGroupMission/model/MappingGroupMission.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserAvatarPurchaseLogRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserAvatarRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserAvatarService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/model/User.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/model/UserAvatar.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/model/UserAvatarPurchaseLog.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/Status.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/EntityDtoMapper.java
  src/main/resources/migration/data.sql
  src/main/resources/migration/togetup-erd.sql
Labels: FEATURE, FIX

#69 [ENV] PR TEMPLATE 생성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ENV
