Repository Wake-up-together-TogetUp/togetup-server, pull requests merged in 2024-02, with the labels that each got.

#90 [FEAT] user stat 결과 경험치를 %로 치환해서 응답
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/model/Alarm.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/auth/service/AuthService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/dto/request/MissionCompleteReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/dto/response/MissionCompleteRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/model/User.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/vo/UserStat.java
  src/main/java/com/wakeUpTogetUp/togetUp/exception/GlobalExceptionHandler.java
  src/main/resources/migration/updates/20240206[user].sql
Labels: FEATURE

#92 [DOCS] 스웨거 명세서에 에러코드 설명 보충
  src/main/java/com/wakeUpTogetUp/togetUp/api/auth/AuthController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/auth/apple/AppleJwtParser.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/auth/service/AppleLoginServiceImpl.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserController.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/Status.java
Labels: DOCS

#93 [DOCS] Error Response 명세서에 작성
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/home/HomeController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/dto/response/GetMissionWithObjectListRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/ObjectDetectionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserAvatarService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserController.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/Status.java
Labels: DOCS

#95 [FIX] 아바타 해금 방식의 변경으로 변화한 유저-아바타 정책 적용
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/AvatarRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/AvatarService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/model/Avatar.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/dto/response/MissionCompleteRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserAvatarRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserAvatarService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/model/User.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/vo/UserProgressResult.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/vo/UserStat.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/Constant.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/Status.java
  src/main/resources/migration/togetup-erd.sql
  src/main/resources/migration/updates/20240222[user avatar].sql
Labels: FIX

#97 [REFACTOR,FIX] user 리팩토링
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserServiceHelper.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/fcmToken/FcmTokenRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/model/User.java
Labels: REFACTOR, FIX
