Repository Wake-up-together-TogetUp/togetup-server, pull requests merged in 2024-03, with the labels that each got.

#99 Fix/avatar list response
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/AvatarTheme.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/vo/UserAvatarData.java
  src/main/resources/migration/data.sql
Labels: D-0

#102 [FEAT] 개발용 미션 수행시 레벨업 응답 API 구현
  src/main/java/com/wakeUpTogetUp/togetUp/api/dev/DevController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/dev/DevService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/dto/response/MissionCompleteRes.java
Labels: FEATURE, D-1

#103 #80 [REFACTOR] 객체 탐지 API 기능 개선 및 리팩토링
  build.gradle
  src/main/java/com/wakeUpTogetUp/togetUp/api/file/FileController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/file/FileService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/file/dto/response/PostFileRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/MissionPerformResult.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/ObjectDetectionResult.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/VisionAnalysisResult.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/model/BoundingBox.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/model/CustomAnalysisEntity.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/model/CustomDetectedObject.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/model/CustomDetectedTag.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/MissionImageService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/ObjectDetectionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/mapper/ObjectDetectedV32Mapper.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/mapper/ObjectDetectedV40Mapper.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/mapper/TagDetectedV40Mapper.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationService.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/Status.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/annotation/validator/ImageFile.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/annotation/validator/ImageFileValidator.java
  src/main/java/com/wakeUpTogetUp/togetUp/config/AzureVision32Config.java
  src/main/java/com/wakeUpTogetUp/togetUp/config/AzureVision40Config.java
  src/main/java/com/wakeUpTogetUp/togetUp/exception/GlobalExceptionHandler.java
  src/main/java/com/wakeUpTogetUp/togetUp/infra/aws/s3/FileService.java
  src/main/java/com/wakeUpTogetUp/togetUp/infra/aws/s3/model/CustomFile.java
  src/main/java/com/wakeUpTogetUp/togetUp/infra/aws/s3/model/ImageContentType.java
  src/main/java/com/wakeUpTogetUp/togetUp/infra/azure/vision/AzureVision32Service.java
  src/main/java/com/wakeUpTogetUp/togetUp/infra/azure/vision/AzureVision40Service.java
  src/main/java/com/wakeUpTogetUp/togetUp/infra/google/fcm/FcmService.java
  src/main/java/com/wakeUpTogetUp/togetUp/infra/google/vision/GoogleVisionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/DateTimeProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/FileUtil.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/FileValidator.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/ImageProcessing/vo/ImageProcessResult.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/ImageProcessor.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/SHA256.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/ValidationRegex.java
Labels: BUG, REFACTOR, FEATURE, D-1

#105 [FIX] AlarmCreateReq의 isVibrate를 타입을 Boolean으로 변경
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/request/AlarmCreateReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/AlarmMigrationMapper.java
Labels: FIX, D-2

#109 [CHORE] 룸, 유저, 노티피케이션, auth의 code smell 제거
  src/main/java/com/wakeUpTogetUp/togetUp/api/auth/LoginType.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/auth/apple/AppleClaimsValidator.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/auth/service/AppleLoginServiceImpl.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/auth/service/AuthService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/PushLogService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/entity/Notification.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/model/Room.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserAvatarService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/model/User.java
Labels: CHORE, D-5

#110 #80 [REFACTOR] 표정 인식 API 리팩토링 및 미션 수행 API 통합
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionFacade.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/CustomAnalysisEntity.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/CustomDetectedFaceAnnotation.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/CustomDetectedObject.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/CustomDetectedTag.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/FaceAnnotationRecognitionResult.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/Letterbox.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/MissionPerformResult.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/ODResult.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/ObjectDetectionModel.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/ObjectDetectionResult.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/VisionAnalysisResult.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/dto/response/MissionPerfomRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/model/BoundingBox.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/model/Coord.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/model/CustomAnalysisEntity.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/model/CustomDetectedObject.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/model/CustomDetectedTag.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/model/Expression.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/model/MissionObject.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/model/MissionType.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/repository/MissionLogRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/repository/MissionObjectRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/repository/MissionRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/MissionImageService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/MissionProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/MissionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/ObjectDetectionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/VisionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/VisionServiceFactory.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/strategy/AnalysisConversionStrategy.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/strategy/MissionImageStrategy.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/strategy/MissionImageStrategyFactory.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/strategy/SimpleConversionStrategy.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/Status.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/annotation/validator/ImageFileValidator.java
  src/main/java/com/wakeUpTogetUp/togetUp/config/ODConfig.java
  src/main/java/com/wakeUpTogetUp/togetUp/exception/BaseException.java
  src/main/java/com/wakeUpTogetUp/togetUp/infra/aws/s3/FileService.java
  src/main/java/com/wakeUpTogetUp/togetUp/infra/aws/s3/model/ImageContentType.java
  src/main/java/com/wakeUpTogetUp/togetUp/infra/azure/vision/AzureVision32Service.java
  src/main/java/com/wakeUpTogetUp/togetUp/infra/azure/vision/AzureVision40Service.java
  src/main/java/com/wakeUpTogetUp/togetUp/infra/azure/vision/mapper/ObjectDetectedV32Mapper.java
  src/main/java/com/wakeUpTogetUp/togetUp/infra/azure/vision/mapper/ObjectDetectedV40Mapper.java
  src/main/java/com/wakeUpTogetUp/togetUp/infra/azure/vision/mapper/TagDetectedV32Mapper.java
  src/main/java/com/wakeUpTogetUp/togetUp/infra/azure/vision/mapper/TagDetectedV40Mapper.java
  src/main/java/com/wakeUpTogetUp/togetUp/infra/google/vision/GoogleVisionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/infra/google/vision/mapper/GoogleVisionMapper.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/ImageProcessor.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/file/FileUtil.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/file/FileValidator.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/image/ImageDrawer.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/image/ImageProcessor.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/image/ImageUtil.java
Labels: BUG, REFACTOR, D-3

#107 [FIX,CHORE] 방장과 관련된 로직 삭제 및 방 탈퇴 로직 수정
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/model/Alarm.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomUserRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomDetailRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomInfoRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/model/Room.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/model/RoomUser.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/EntityDtoMapper.java
  src/main/resources/migration/updates/20240326[room_user].sql
Labels: CHORE, FIX, D-2
