Repository Wake-up-together-TogetUp/togetup-server, pull requests merged in 2024-06, with the labels that each got.

#139 #137 [ENV] 운영환경 CI/CD
  .github/workflows/cicd_prod.yml
Labels: ENV, D-2

#140 #137 개발 환경 ci/cd 추가, 스웨거 요청 url수정
  .github/workflows/cicd_dev.yml
  src/main/java/com/wakeUpTogetUp/togetUp/config/OpenApiConfig.java
Labels: ENV, D-2

#136 [FEAT] 조건에 따른 아바타 대사 가져오기 구현
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/application/AvatarSpeechProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/application/RandomFoodProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/application/SpeechStrategyFactory.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/application/UserAvatarQueryService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/application/UserAvatarService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/application/UserAvatarValidationService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/application/strategy/BasicSpeechStrategy.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/application/strategy/FoodSpeechStrategy.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/application/strategy/SpeechStrategy.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/application/strategy/TimeSpeechStrategy.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/domain/Avatar.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/domain/AvatarSpeech.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/domain/AvatarSpeechCondition.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/domain/AvatarTheme.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/domain/UserAvatar.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/model/AvatarSpeechCondition.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/repository/AvatarRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/repository/AvatarSpeechRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/repository/UserAvatarRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/util/KoreanLunarCalendar.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/util/LunarDate.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/util/RandomFoodProviderImpl.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/domain/User.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/Status.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/DateTimeProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/EntityDtoMapper.java
  src/main/resources/migration/data.sql
Labels: FEATURE, D-3

#141 [FEATURE] 비활성화된 알람도 포함하는 알람 타임라인 조회 기능 구현
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/response/AlarmTimeLineRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/model/Alarm.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/home/HomeController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/model/MissionLog.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/MissionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/DateTimeProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/file/FileUtil.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/EntityDtoMapper.java
  src/main/resources/migration/updates/20240603[mission_log].sql
Labels: FEATURE, D-2

#144 #143 [FEAT] 아바타 해금시 fcm noti 보내기
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/MissionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationDataKeyType.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationDataValueType.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/vo/AvatarUnlockedNotificationEvent.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/vo/RoomMissionLogNotificationEvent.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/fcmToken/FcmTokenRepository.java
Labels: FEATURE, D-3
