Repository Wake-up-together-TogetUp/togetup-server, pull requests merged in 2024-07, with the labels that each got.

#145 [REFACTOR] 알람 타임라인 조회 API 성능 개선
  build.gradle
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/domain/AlarmType.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/response/AlarmSimpleRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/model/Alarm.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/repository/AlarmQueryRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/repository/AlarmQueryRepositoryImpl.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/repository/AlarmRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/service/AlarmQueryService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/service/AlarmService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/service/AlarmValidationService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/home/HomeController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/model/MissionLog.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/MissionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomQueryService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/annotation/LogExecutionTime.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/aspect/LoggingAspect.java
  src/main/java/com/wakeUpTogetUp/togetUp/config/QuerydslConfig.java
  src/test/java/com/wakeUpTogetUp/togetUp/alarm/AlarmControllerTest.java
Labels: REFACTOR, D-3

#146 [FEATURE] 미션 수행 기록 별도 파일에 로깅
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/FaceAnnotationRecognitionResult.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/ObjectDetectionResult.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/VisionAnalysisResult.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/MissionService.java
  src/main/resources/logback-spring.xml
Labels: FEATURE, D-3

#147 [FEATURE] 미션 수행 API 처리율 제한 구현
  build.gradle
  src/main/java/com/wakeUpTogetUp/togetUp/TogetUpApplication.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/strategy/MissionImageStrategyFactory.java
Labels: FEATURE, D-3

#148 [FEATURE] 그룹 인원 제한 락 구현
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomUserRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/model/Room.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/Status.java
Labels: REFACTOR, FEATURE, D-3

#149 [FEATURE] notification get api, 읽음 처리 api, 삭제 api 추가
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/DataMapToStringConverter.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationEventHandler.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationLogService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/dto/response/NotificationListRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/dto/response/NotificationRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/entity/Notification.java
  src/main/resources/migration/updates/20240728[notification].sql
Labels: FEATURE, D-3
