Repository Wake-up-together-TogetUp/togetup-server, pull requests merged in 2024-09, with the labels that each got.

#160 [CHORE,STYLE]: room에 들어갈 때 roomId 응답에 추가
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomJoinRes.java
Labels: CHORE, D-1

#163 #161 [FEAT] 타임존에 따른 시간 반환 기능 구현
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmQueryController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/auth/AuthController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/application/strategy/TimeMakeSpeechStrategy.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/controller/AvatarSpeechController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/dev/DevController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/entity/Notification.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserController.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/Status.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/DateTimeProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/TimeFormatter.java
Labels: DOCS, REFACTOR, FEATURE, D-2

#165 [FIX] 타임라인 목록 중복 제거
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmQueryController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/response/AlarmSimpleRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/repository/AlarmRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomController.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/EntityDtoMapper.java
Labels: FEATURE, FIX

#166 #133 [REFACTOR] 알람 조회 DTO 불필요한 필드 삭제 및 네이밍 리팩터링
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/controller/AlarmController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/controller/AlarmQueryController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/controller/dto/request/AlarmCreateReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/controller/dto/request/AlarmsDeactivateReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/controller/dto/request/PatchAlarmReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/controller/dto/request/PostAlarmReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/controller/dto/response/AlarmDetailRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/controller/dto/response/AlarmRoomRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/controller/dto/response/AlarmSimpleRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/controller/dto/response/AlarmTimeLineRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/repository/AlarmQueryRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/repository/AlarmQueryRepositoryImpl.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/repository/AlarmRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/service/AlarmQueryService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/service/AlarmService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/dto/response/GetMissionWithObjectListRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/dto/response/MissionObjectRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/dto/response/MissionRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/request/RoomReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/Constant.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/AlarmMigrationMapper.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/EntityDtoMapper.java
  src/test/java/com/wakeUpTogetUp/togetUp/alarm/AlarmControllerTest.java
Labels: REFACTOR, D-2

#169 #167 #170 [FEAT] Jacoco 리포트, SonarCloud 설정 및 JAVA 17로 버전 업그레이드
  .github/workflows/ci_dev.yml
  .github/workflows/ci_pipeline.yml
  .github/workflows/cicd_dev.yml
  .github/workflows/cicd_prod.yml
  build.gradle
  src/test/java/com/wakeUpTogetUp/togetUp/TogetUpApplicationTests.java
Labels: FEATURE, ENV, D-2

#174 #173 [ENV] : CI/CD 파이프라인 개선 - Docker 통합 및 Docker Compose 도입, Gradle 캐싱
  .github/workflows/cicd_dev.yml
  .github/workflows/cicd_prod.yml
  Dockerfile
  docker-compose/docker-compose-dev.yml
  docker-compose/docker-compose-prod.yml
Labels: ENV, D-3
