Repository Wake-up-together-TogetUp/togetup-server, pull requests merged in 2024-08, with the labels that each got.

#150 [FIX]: roomlist 에서 똑같은 room 여러개 반환하는 에러 해결, missionObject여러개 반환 해 NonUniqueResultException나는 에러 해결
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/repository/AlarmRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomQueryRepositoryImpl.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomQueryService.java
Labels: FIX, D-2

#152 [CHORE]: 그룹알람 생성 시 Id 반환하게 수정
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
Labels: CHORE, D-2

#153 [CHORE]: RoomDetailRes, RoomInviteInfoRes에 미션 영어이름 추가
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomQueryService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomDetailRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomInviteInfoRes.java
Labels: CHORE, D-2

#151 [FEAT] 알람 icon을 미션 icon으로 대체
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/request/PatchAlarmReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/request/PostAlarmReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/response/AlarmDetailRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/response/AlarmSimpleRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/model/Alarm.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/repository/AlarmQueryRepositoryImpl.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/repository/AlarmRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/service/AlarmQueryService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/service/AlarmService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/AlarmMigrationMapper.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/EntityDtoMapper.java
  src/main/resources/migration/updates/20240813[alarm].sql
Labels: FEATURE, D-2

#158 [FIX,STYLE]: deprecated된 메소드 수정 및 구글 코드 스타일 적용
  src/main/java/com/wakeUpTogetUp/togetUp/infra/fcm/FcmService.java
Labels: BUG, D-2
