Repository Wake-up-together-TogetUp/togetup-server, pull requests merged in 2024-05, with the labels that each got.

#125 [FEAT] 유저 아바타 응답에 아바타 기본 대사 포함 기능 구현
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/application/UserAvatarService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/dto/response/UserAvatarResponse.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/model/Avatar.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/model/AvatarSpeech.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/model/AvatarSpeechCondition.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/Status.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/EntityDtoMapper.java
  src/main/resources/migration/data.sql
Labels: FEATURE, D-2

#126 [FEAT] 버전에 따라 앱 스토어 URL를 가져오는 API 구현
  src/main/java/com/wakeUpTogetUp/togetUp/api/dev/AppVersionHistoryRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/dev/AppVersionProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/dev/DevController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/dev/dto/response/AppStoreUrlRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/dev/model/AppVersionHistory.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/dev/util/VersionComparator.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/Status.java
  src/main/resources/migration/data.sql
  src/main/resources/migration/togetup-erd.sql
  src/main/resources/migration/updates/20240502[app_version_history].sql
Labels: FEATURE, D-2

#127 #64 [ENV] github action을 이용한 CI/CD 구축
  .github/workflows/cicd_dev.yml
Labels: ENV, D-2

#130 [ENV] CI workflow application.yml 파일 생성 에러 해결
  .github/workflows/ci_dev.yml
Labels: ENV, D-2

#128 [FEAT] alarm 일괄 비활성화 api 구현
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmValidationService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/request/AlarmsDeactivateReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/common/Status.java
Labels: FEATURE, D-2

#134 [REFACTOR] user 레벨 업 및 기타 작업 리팩터링
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/model/Alarm.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/auth/dto/response/LoginRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/auth/service/AuthService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/application/UserAvatarQueryService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/application/UserAvatarService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/application/model/UnlockAvatarResult.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/model/UserAvatar.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/dev/DevController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/dev/DevService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/dto/response/MissionCompleteRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/model/MissionLog.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/MissionService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/notification/vo/RoomMissionLogNotificationEvent.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/model/RoomUser.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserProgressService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserServiceHelper.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/domain/User.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/domain/UserProgressCalculator.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/domain/model/UserProgressResult.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/domain/vo/UserStat.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/fcmToken/FcmToken.java
Labels: REFACTOR, D-2

#135 [FIX] 객체 탐지 결과 도출 시 단어의 포함으로 성공하는 에러 해결
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/CustomDetectedObject.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/CustomDetectedTag.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/FaceAnnotationRecognitionResult.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/ObjectDetectionResult.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/VisionAnalysisResult.java
  src/main/java/com/wakeUpTogetUp/togetUp/infra/azure/vision/AzureVision32Service.java
  src/main/java/com/wakeUpTogetUp/togetUp/infra/azure/vision/AzureVision40Service.java
  src/main/resources/migration/data.sql
Labels: BUG, FIX, D-2
