Repository Wake-up-together-TogetUp/togetup-server, pull requests merged in 2024-04, with the labels that each got.

#113 [FIX] 알람에 is_deleted추가 및 soft delete 칼럼 변경 (is_activated-> is_deleted)
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/model/Alarm.java
  src/main/resources/migration/updates/20240402[alarm].sql
Labels: FIX, D-2

#114 [FIX] 애플로그인 수정, 이메일 길이 수정
  src/main/java/com/wakeUpTogetUp/togetUp/api/auth/service/AppleLoginServiceImpl.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/auth/service/AuthService.java
  src/main/resources/migration/togetup-erd.sql
  src/main/resources/migration/updates/20240405[user].sql
Labels: D-3

#115 [FEAT] 일회성 알람을 브리핑 보드에 반영하는 기능 구현
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/request/AlarmCreateReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/request/PatchAlarmReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/request/PostAlarmReq.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/response/GetAlarmRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/model/Alarm.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/auth/AuthUserResolver.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/home/HomeController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserValidationService.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/AlarmMigrationMapper.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/EntityDtoMapper.java
  src/main/resources/migration/updates/20240406[alarm].sql
Labels: FEATURE, D-2

#119 #106 [RESTRUCTURE] room에 cqrs 패턴 적용
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/model/Alarm.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/model/MissionLog.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/mission/repository/MissionLogRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomController.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomQueryRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomQueryRepositoryImpl.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomQueryService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/UserCompleteType.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomDetailRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomInviteInfoRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomUserMissionLogRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/UserLogData.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/UserProfileData.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/model/Room.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserRepository.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/DateTimeProvider.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/TimeFormatter.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/EntityDtoMapper.java
Labels: D-2, RESTRUCTURING

#118 [FEAT] 아바타 테마 한국어 이름 가져오기
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/dto/response/UserAvatarResponse.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/model/Avatar.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/model/AvatarTheme.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomQueryService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/UserProfileData.java
  src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/EntityDtoMapper.java
  src/main/resources/migration/data.sql
  src/main/resources/migration/togetup-erd.sql
  src/main/resources/migration/updates/20240409[avatar_speech].sql
  src/main/resources/migration/updates/20240412[avatar].sql
Labels: FEATURE, D-2

#120 [FIX] : 순환종속성으로 인한 무한재귀문제 해결
  src/main/java/com/wakeUpTogetUp/togetUp/api/users/model/User.java
Labels: D-2

#121 [FIX] : dto 아바타 테마 설명 수정
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomUserMissionLogRes.java
  src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/UserProfileData.java
Labels: FIX, D-2

#124 #123 [FIX] : 도메인 변경 스웨거에 반영
  src/main/java/com/wakeUpTogetUp/togetUp/config/OpenApiConfig.java
Labels: FIX, D-2
